# Generated by Django 2.0.6 on 2020-07-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Fuel')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_data_time', models.DateTimeField(verbose_name='Reading time')),
                ('consumption', models.DecimalField(decimal_places=4, max_digits=20)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Meter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='readings',
            unique_together={('meter_id', 'reading_data_time')},
        ),
    ]
